### ISSUE TITLE
How to set outer layer of the quad view with grey transparent overlay

### ISSUE THREAD

**Issue by dshark95** [microblink/blinkid-android#296]
### Description
Hi, I am new to native android.
How to set the outer layer of the quad view with grey transparent overlay? 

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version: 6.1.0 **

**Device model: Samsung A50**

**Device Android version: Android 12**

**Device ABI (processor architecture, e.g. ARMv7):**

This is the sample app that I create
![photo_2023-07-18_00-29-25](https://github.com/BlinkID/blinkid-android/assets/60464500/798e1fd8-d988-4f13-80bd-d95a291776ce)

I need to do something like this:
<img width="152" alt="Screenshot 2023-07-18 at 12 31 13 AM" src="https://github.com/BlinkID/blinkid-android/assets/60464500/51cc518c-033a-46c3-971f-82efa2acad0f">

any ideas?

**Comment by Brankacro** [comment]
Hello @dshark95.
Regarding the BlinkIdUISettings and overlay, please find more details on the following [link](https://github.com/BlinkID/blinkid-android#-available-activities-and-overlays) and let us know if the provided info helped.
Best regards.

**Comment by dshark95** [comment]
Hi @Brankacro , do you have any code sample regarding to this to that I can study on that?

**Comment by Brankacro** [comment]
HI @dshark95, here you can find [BlinkID-CustomUISample](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-CustomUISample). 
We highly recommend using our[ built in UI settings](https://github.com/BlinkID/blinkid-android#blinkid-ui-component) which are a result of many years of user experience research and usability testing. You can see[ here which elements](https://github.com/BlinkID/blinkid-android#scan-overlay-theming) can be customized within the built in UI settings. You can also go your own route and[ customize the UI completely](https://github.com/BlinkID/blinkid-android#recognizer-runner-view), but then you would have to do it completely on your own since we can’t provide support for custom UI/UX.
Hope this info helps. Please let us know in case of any additional questions.

**Comment by Brankacro** [comment]
Hi @dshark95. Since this topic is inactive, we'll go ahead and close it. In case of any additional questions or concerns, feel free to reach us at support@microblink.com and we'll be glad to assist. Best regards.
