### ISSUE TITLE
com.microblink.blinkid.licence.exception.InvalidLicenceKeyException

### ISSUE THREAD

**Issue by akshaykumar112** [microblink/blinkid-android#316]
java.lang.RuntimeException: Unable to create application packagename.MyApplication: com.microblink.blinkid.licence.exception.InvalidLicenceKeyException: Provided licence is invalid for product BlinkID. It is valid only for application ID 'packagename, for products 'Capture', on platform 'Android'. Please contact support for more information.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7299)

**Comment by mparadina** [comment]
Hi @akshaykumar112 

From the shared exception, it looks like you've entered a license key for the [Capture SDK](https://github.com/BlinkID/capture-android), in the [BlinkID SDK](https://github.com/BlinkID/blinkid-android).
Can you contact us directly at support@microblink.com so that we can inspect the license key?
